name: Makefile CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: actions/checkout@v2
            - uses: MunifTanjim/setup-neovim-action@v1

            - name: Run tests
              run: make test
